### ISSUE TITLE
已激活用户，更新最新版后变成未激活状态了。

### ISSUE THREAD

**Issue by noir1216** [sh2288/transer#10]
很长时间没用（之前版本是3.*），昨天打开软件提示有更新，于是就覆盖更新到了最新版。
然后就提示需要重新激活了，用之前的激活码没法激活。
没换电脑，电脑也没升级任何硬解。就只是更新了软件就提示需要重新激活了。
本来打算加群反馈的，但是加了两个分群都没人审核通过，只能来这里反馈了
![123](https://github.com/sh2288/transer/assets/44556349/05a6ed05-19b1-48d2-8bc1-566b0563b99e)

**Comment by sh2288** [comment]
ok!加QQ群574054671,私聊群主即可
