### ISSUE TITLE
翻译结果自带回车

### ISSUE THREAD

**Issue by Orienser** [sh2288/transer#2]
text模式，翻译后导出的剧本会在每行译文后都带一个回车，影响文本排版。

原文：
![image](https://user-images.githubusercontent.com/13484542/129219201-401e249e-47cb-453d-8623-21ccc3f32910.png)
翻译结果：
![image](https://user-images.githubusercontent.com/13484542/129219355-f72eba56-c306-497d-b336-ddcaab0e2001.png)
导出剧本：
![image](https://user-images.githubusercontent.com/13484542/129219467-ba63e5c2-8ad5-46b5-adfc-4c4258f63275.png)

**Comment by sh2288** [comment]
你这样的文本不需要过滤正则

**Comment by sh2288** [comment]
你换个正则试试

**Comment by sh2288** [comment]
可能我没写明白,**行间过滤正则**的用意是跳过,如果可以把样本发到群里

**Comment by Orienser** [comment]
找出原因了，这种自带回车的情况只有在打包字数为0时会发生，如下图设为2000时，译文是正常的。
![image](https://user-images.githubusercontent.com/13484542/129359186-79ac9f21-868f-4d34-8626-2e709928faaa.png)
![image](https://user-images.githubusercontent.com/13484542/129359209-c0f9ba09-9787-4787-a5c0-9aa370a406da.png)

附原文文件：
[text.txt](https://github.com/sh2288/transer/files/6982465/text.txt)

**Comment by sh2288** [comment]
感谢,反馈bug,我会在以后修复,为0时表示不打包翻译(按行翻译),可能这个方法写的有疏漏
