### ISSUE TITLE
Text模式的提取正则为空时导出的剧本是原文

### ISSUE THREAD

**Issue by Orienser** [sh2288/transer#3]
text模式，提取正则置空（采用默认值），导出的剧本和译文一样。

原文：
![image](https://user-images.githubusercontent.com/13484542/129219959-7a909556-7523-46aa-a014-0cb415334e89.png)
翻译结果：
![image](https://user-images.githubusercontent.com/13484542/129220176-a1cb64a4-1683-4233-ac73-be40876c8fcb.png)
导出剧本：
![image](https://user-images.githubusercontent.com/13484542/129220062-4306e4bf-0ded-4a1e-bb9d-6d44f71712b3.png)

**Comment by sh2288** [comment]
已经发现此bug,正则为空时,确实
过几天修复(下个版本)

**Comment by sh2288** [comment]
这个bug,新版2021-08-16已经修复,到release下新版
