### ISSUE TITLE
翻译面板上有翻译文本但是导出时却没有

### ISSUE THREAD

**Issue by jiekeccs** [sh2288/transer#4]
![image](https://user-images.githubusercontent.com/61866533/129763389-62142b7d-a7f2-474d-8239-eca17c7bc5ed.png)
![image](https://user-images.githubusercontent.com/61866533/129763510-4f395e34-2388-4020-a54f-53b07737086d.png)
![image](https://user-images.githubusercontent.com/61866533/129763595-bd75aa4e-25c8-4c44-9f32-83721694c478.png)
翻译测试结果，是正则的原因吗？

**Comment by sh2288** [comment]
这个文本前面貌似有特殊符号,可能是tab符号
什么版本,请用最新版,如果还有问题,请加QQ群 706514743,把样本发给我

**Comment by sh2288** [comment]
这个问题已经修正,请下载最新版2021-08-24
