### ISSUE TITLE
用着还不错，提几点缺失的功能

### ISSUE THREAD

**Issue by wefriend** [sh2288/transer#5]
用着还不错，提几点缺失的功能：
1. 快捷键。没见到有快捷键，要鼠标点呀点地一行行翻译，这。。。用着太辛苦了。能自定义快捷键就更好了。
2. 多行选中时候，右键点翻译，只翻译了最后选中那行，并没有把扫黑的全部翻译。

因为我刚好有个需求，翻译只翻译部分文件，并不是整个文件翻译。
因缺失上述两点功能，所以用着还是很辛苦。尽管减轻了部分工作负担，但是减轻得并不是很多。点鼠标太辛苦了😭

建议加上上述功能。

谢谢你的分享。

**Comment by sh2288** [comment]
大哥,你没看到上面有--翻译所有剧本--的按钮么
