### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by Dclef** [sh2288/transer#6]
**翻译后的文件如果再重新打开的话，只会在原始文本上显示，希望能修复一下**

**翻译完成的文件**

![Snipaste_2022-02-13_22-02-42](https://user-images.githubusercontent.com/42974381/153756690-7aee77b4-9ccc-442e-a2e8-fb7d6272afce.png)

**重新打开后的文件**
![Snipaste_2022-02-13_22-00-26](https://user-images.githubusercontent.com/42974381/153756621-f37973fe-6ccc-4a2b-998b-7e990cc598fc.png)

**Comment by sh2288** [comment]
额...
感谢反馈
