### ISSUE TITLE
txt文件无法提取文字

### ISSUE THREAD

**Issue by zxcec** [sh2288/transer#8]
行匹配正则和行间过滤都是空的，输出编码选utf16和8都不能提取
版本24.02.05
[【中英双语字幕】齐泽克：你只有足够蠢才能看到 2017.5.17en.txt](https://github.com/sh2288/transer/files/14194471/2017.5.17en.txt)
[1261703343-1-192en.txt](https://github.com/sh2288/transer/files/14194472/1261703343-1-192en.txt)

**Comment by sh2288** [comment]
可能是编码无法识别,请自行转utf-8再试,或加群使用最新的测试版本,测试版已支持SRT字幕格式直读

**Comment by sh2288** [comment]
![正则提取](https://github.com/sh2288/transer/assets/30304404/7a4ed5c5-9021-46cd-a9e3-0584f6c2aa9f)
刚试了一下,没问题啊~
加Q群574054671有最新版

**Comment by zxcec** [comment]
发现是和avast不兼容，在avast防护模式开启时不能提取文本，其他功能一切正常
